<?php

/**
 * @file
 * Contains islandora_search_processor.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function islandora_search_processor_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the islandora_search_processor module.
    case 'help.page.islandora_search_processor':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Islandora Search Processors') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function islandora_search_processor_theme() {
  return [
    'islandora_search_processor' => [
      'render element' => 'children',
    ],
  ];
}
